image: weyforth/drone-docker
env:
  - LOG=file
script:
  - tools/pre_deploy
branches:
  - master
  - docker
deploy:
  bash:
    script:
      - ssh deploy@178.62.42.241 'rm -rf app-build'
      - scp -o StrictHostKeyChecking=no -P 22 -r . deploy@178.62.42.241:app-build/
      - ssh deploy@178.62.42.241 app-build/tools/deploy
    when:
      branch: docker
notify:
  email:
    recipients:
      - build@mikefarrow.co.uk
