storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  volumes_from:
    - storage
  restart: always
  environment:
    POSTGRES_PASSWORD: ${WPF_POSTGRES_PASSWORD}

fpm:
  extends:
    file: docker-compose-common.yml
    service: fpm
  links:
    - db
  volumes_from:
    - storage
    - data
  restart: always
  environment:
    DB_PASSWORD: ${WPF_POSTGRES_PASSWORD}

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - fpm
    - db
  volumes_from:
    - storage
    - data
  restart: always

artisan:
  extends:
    file: docker-compose-common.yml
    service: artisan
  links:
    - db
  volumes_from:
    - storage
    - data
  environment:
    DB_PASSWORD: ${WPF_POSTGRES_PASSWORD}

fileaccess:
  extends:
    file: docker-compose-common.yml
    service: fileaccess
  volumes_from:
    - storage
    - data
