storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  volumes_from:
    - storage
  restart: always
  env_file:
    - /home/deploy/db.env

fpm:
  extends:
    file: docker-compose-common.yml
    service: fpm
  links:
    - db
  volumes_from:
    - storage
    - data
  restart: always
  env_file:
    - /home/deploy/db.env
    - /home/deploy/web.env

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - fpm
    - db
  volumes_from:
    - storage
    - data
  restart: always

artisan:
  extends:
    file: docker-compose-common.yml
    service: artisan
  links:
    - db
  volumes_from:
    - storage
    - data
  env_file:
    - /home/deploy/db.env
    - /home/deploy/web.env

fileaccess:
  extends:
    file: docker-compose-common.yml
    service: fileaccess
  volumes_from:
    - storage
    - data
