#!/bin/bash

source app-build/tools/_functions

set -e

COMPOSE_FILE="docker-compose-production.yml"

if [[ -d app ]]; then

	cd app

	heading "Removing data"
	COMPOSE_FILE="$COMPOSE_FILE" docker-compose run --rm data rm -rf /data/www

	tools/stop production

	cd ../

fi

heading "Copying files"

rm -rf app && cp -r app-build app && echo "done"

cd app

tools/start production
tools/install production

echo ""
