#!/bin/bash

source tools/_functions

set -e

install_env="local"

if [[ "$1" != "" ]];
	then
	install_env="$1"
fi

[ -t 1 ] || params="-T"

heading "Database"
docker-compose -f docker-compose-tools.yml run $params --rm buildtools ../tools/dbisup

heading "Installing"

# Laravel equivalent?
if ! $(tools/wp core is-installed); then

	echo "Migrating and seeding database"
	tools/artisan migrate
	tools/artisan db:seed

else

	echo "Already Installed, only migrating"
	tools/artisan migrate

fi
