#!/bin/bash

source tools/_functions

set -e

install_env="local"

if [[ "$1" != "" ]];
	then
	install_env="$1"
fi

[ -t 1 ] || params="-T"

heading "Database"
docker-compose -f docker-compose-tools.yml run $params --rm buildtools ../tools/dbisup

heading "Installing"

set +e
docker-compose -f docker-compose-tools.yml run $params --rm buildtools cat /storage/.migrated  &> /dev/null
migrated=$?
set -e

if [[ $migrated != 0 ]]; then

	echo "Migrating and seeding database"
	tools/artisan migrate
	tools/artisan db:seed

	docker-compose -f docker-compose-tools.yml run $params --rm buildtools touch /storage/.migrated

else

	echo "Already Installed, only migrating"
	tools/artisan migrate

fi
