#!/bin/bash

source tools/_functions

set -e

install_env="local"

if [[ "$1" != "" ]];
	then
	install_env="$1"
fi

[ -t 1 ] || params="-T"

heading "Database"
tools/run buildtools ../tools/dbisup

heading "Installing"

function artisan {
	run_env=$install_env

	if [[ "$run_env" == "local" ]];
		then
		run_env="tools"
	fi

  docker-compose -f "docker-compose-${run_env}.yml" run artisan $params --rm "$@"
}

set +e
tools/run fileaccess cat /storage/.migrated  &> /dev/null
migrated=$?
set -e

if [[ $migrated != 0 ]]; then

	echo "Migrating and seeding database"

	artisan migrate --force
	artisan db:seed --force

	tools/run fileaccess touch /storage/.migrated

else

	echo "Already Installed, only migrating"
	artisan migrate --force

fi
