#!/bin/bash

source tools/_functions

build_env="local"

if [[ "$1" != "" ]];
	then
	build_env="-$1"
fi

if [[ "$build_env" != "local" ]]; then
	heading "Pulling Docker images"
	COMPOSE_FILE="$COMPOSE_FILE" docker-compose pull >/dev/null
fi

heading "Starting"

if [[ $(COMPOSE_FILE="$COMPOSE_FILE" docker-compose ps | grep _nginx) ]]; then

	COMPOSE_FILE="$COMPOSE_FILE" docker-compose up --no-recreate -d db fpm nginx

else

	COMPOSE_FILE="$COMPOSE_FILE" docker-compose up -d

fi
